apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jxps
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-jxps@sha256:05b037e10655cc0f72a54e00032ee10341cc42afcbaa05d7d9033f8919dce3ea
        name: my-nodejs
        resources: {}
status: {}
